### ISSUE TITLE
Diagram is not updated after refactoring

### ISSUE THREAD

**Issue by Stefku** [Stefku/intellij-reference-diagram#2]
Goto a node representing a method and rename it.
The method has been renamed, but the diagram has not been updated.

**Comment by Stefku** [comment]
Look at com.intellij.diagram.PsiDiagramNode. There a SmartPsiElementPointer is used, which returns the updated PsiElement.

**Comment by ivankolev** [comment]
Hey Stefku, might be a really dumb question, but how do I start this plugin?! I have it installed alright, but I can't find the button/menu that opens the diagram window?

**Comment by Stefku** [comment]
Hi @ivankolev, same as creating a class diagram: CTRL+ALT+SHIFT+U (on windows)
