### ISSUE TITLE
how do you open this in idea

### ISSUE THREAD

**Issue by saurabh0683** [Stefku/intellij-reference-diagram#50]
Hi
while browsing plugins i found it interesting and decided to try it. But could not find any way i could actually see it in action. whats menu or whats keyboard shortcut???

**Comment by Stefku** [comment]
Hi there, you open it like the other diagramm types. On windows with ctrl + shift + alt + U. 
Hope that helps. 
Cheers 
Stefku 

von unterwegs gesendet

**Comment by saurabh0683** [comment]
Hi Stefan,

Thanks for immediate reply. I installed it and right clicked on class which
shows diagrams. At this point it shows java class diagram but not any other
option. Also can you also suggest for mac?

Regards,
Saurabh Akshekar
Mob - 9920016305

**Comment by Stefku** [comment]
Have you the Community Ort ultimate version? You need ultimate.

von unterwegs gesendet

**Comment by saurabh0683** [comment]
yes i do have latest version
wats keyboard shortcut or menu option for opening diagram
when i open context menu on class, in digrams menu it only shows java class
digrams

Regards,
Saurabh Akshekar
Mob - 9920016305

**Comment by Stefku** [comment]
Hi Saurabh

My build version of IntelliJ is #IU-145.1617. I can open the Method Reference Diagram with action "Show UML Diagram". Either it can be found with "Find Action" CTRL+SHIFT+A (Windows) / CMD+SHIFT+A (Mac), or directly with CMD+ALT+SHIFT+U (Mac) / Windows short cut is not on my mind.

To be able to open the reference diagram you have to be in a java file. Sure :)

If you try to do that and you cannot choose the diagram type Method Reference Diagram, do you get an exception in the log file? See Help -> Show log file.

Cheers
Stefku

**Comment by Jofsey** [comment]
I can confirm this problem. But it's unstable. There was no `Method Reference Diagram` item, but then it appeared without any related actions from my side.

**Comment by saurabh0683** [comment]
Hi Jose,

Same for me. Yesterday only I tried plugin again n it worked. May der is
some issue or idea version compatibility. Issues like this make me wonder
many such plugins should be made IDE independent like say maven plugin and
output in XML/svg

I would be happy to contribute for this.

**Comment by Stefku** [comment]
I'm not sure, but maybe the diagram is not available during indexing?
If you guys have any clue why the Method Reference Diagram does not appear sometimes, let me know.
