### ISSUE TITLE
Can't find the plugin in repository

### ISSUE THREAD

**Issue by Jofsey** [Stefku/intellij-reference-diagram#51]
I use Intellij IDEA Ultimate 2016.1.3 but can't find the plugin in repository. So it's available only by 'install from file'.
![image](https://cloud.githubusercontent.com/assets/3617466/16454604/0a40af0c-3e1a-11e6-9674-eeb88e762e1e.png)

**Comment by Stefku** [comment]
Hi Jofsey, that's right. When you search for "java referen" you'll find nothing. That's a problem with the search algorithm. Because, when you search for "java method reference" then you'll see the plugin.
Does this help?
