### ISSUE TITLE
Indicate on the documentation how to start a diagram

### ISSUE THREAD

**Issue by spaceCamel** [Stefku/intellij-reference-diagram#60]
I've installed the plugin but can't find how to open the diagram.
I thought I would just right click on an element to find "Find References" or something similar but I couldn't tell what action I'm supposed to invoke.

The documentation also doesn't seem to tell how to open the diagram.

Can you indicate what action to look for?

**Comment by Stefku** [comment]
Thanks for this hint. I updated the README.md with 8faae39fad1987bb0523dc97f71a63c8fc730966.
