### ISSUE TITLE
Plugin is installed and used to work, but not anymore under IntelliJ 2021.1

### ISSUE THREAD

**Issue by 62mkv** [Stefku/intellij-reference-diagram#71]
I have this plugin installed and it does not indicate any problems (although I am not sure, how do you achieve that, if the latest release is from 2019)

so when I click Ctrl+Alt+Shift+U, when inside the class, then I get only 2 items in the popup menu: 

![image](https://user-images.githubusercontent.com/5255127/121494718-a6e85280-c9e1-11eb-9cc3-20ae65630c79.png)

are there any more specific requirements to be able to build a method graph diagram ?

**Comment by Stefku** [comment]
Hi @62mkv, with IntelliJ 2021 the plugin has a compatibility issue and does not start. I'm working on it.
See #70.
