### ISSUE TITLE
Install Error: `Plugin Java method Reference Diagramm depends on unknown plugin com.intellij.diagram`

### ISSUE THREAD

**Issue by schittli** [Stefku/intellij-reference-diagram#75]
Hello

Thank you for sharing your great work!

Unfortunately, Release 3.1.1 can not be installed, during installation one gets:
![image](https://user-images.githubusercontent.com/8282673/134822403-55937462-e323-4d66-8065-10d82fbe2133.png)

After restarting IntelliJ, it reports:

![image](https://user-images.githubusercontent.com/8282673/134822495-7ef73987-8dfe-409e-9083-d4e59e19b73c.png)

Could it be that the plugin is not compatible with IntelliJ Community Edition?

Thanks a lot, kind regards,
Thomas

**Comment by Stefku** [comment]
Yes, this plugin is not compatible with community edition.

**Comment by Stefku** [comment]
The reason is, that I used the UML capability of IDEA which is a licensed library and thus jetbrains just has it in pro version.
For me it would be better to have the plugin be compatible with community edition, but then I have to implement the graph and the integration with Goto Source etc. for my self. For that, I do not have the time.

**Comment by schittli** [comment]
Hello @Stefku 
thanks a lot for your help!, 
I had unfortunately overlooked that you explicitly mentioned 'This plugin for IntelliJ IDEA **Ultimate**...' in the readme.md. I actually always read information like readme.md by skimming it and I focus on the headings.


Would it be possible for you to mention it a bit more clearly in these two places, so that community edition users don't even try to test it? (Please see then screenshot)

**(1)** The About text does just talk about IntelliJ
**(2)** if possible, it would probably be good if Ultimate is written in bold in the introductory sentence: _"This plugin for IntelliJ IDEA **Ultimate** helps to get an overview "_


![image](https://user-images.githubusercontent.com/8282673/135162488-1ce079c3-da3f-4427-9bcd-b9aeb3ef6380.png)


Thanks a lot, kind regards,
Thomas

**Comment by Stefku** [comment]
Thanks @schittli for the hint. I updated the recommended texts.
